### ISSUE TITLE
HCS changes stage coordinate system

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#26]
Currently the HCS plugin calibration changes the XYStage adapter's origin and saves all positions in terms of this new calibration. However since this new origin is not applied after restarting micromanager, any position list that was saved from the HCS plugin will not be valid unless the user changes the XYStage adapter origin again.

Rather than having the plugin change the adapter's origin it seems like it would be best to leave the origin as the device adapter initially defines it to avoid interfering with other saved position lists or coordinate dependent behavior. Instead the plugin calibration could internally save an offset that it then applies to positions before sending them to the position list.

Aside from avoiding potential confusion by changing the stage's coordinate system this would also allow the plugin to save the calibration offset as a setting, that way a user would ideally only need to run this calibration once.

This is something I can work on, I just wanted to make sure my thinking made sense before spending time on it.

**Comment by nicost** [comment]
This makes sense for encoded stages that remember their position between restarts.  Regretfully, there are plenty of stages out there that do not remember their position, and start at 0,0 whenever you switch it on.  So, those kind of stages will always need to be re-calibrated.  

Regretfully, MM can not distinguish those kind of stages.  Since it is extremely easy to cause major financial damage when moving the XY stage to positions it should not be going, we have always taken the safest approach and treated all stages the same.  

So, I think that you can go ahead, but should make this new behavior opt-in, i.e. the default should be the current behavior, but there can be an option somewhere that switches to the behavior you describe.  Your decision if it is worth the effort.

**Comment by nanthony21** [comment]
I see what you mean about the non-homing stages. From a design standpoint though does it make sense to have a specialized plugin like the HCS plugin making system-wide changes such as device adapter calibration?

Would it make more sense to split the device adapter calibration into a separate functionality? There could be a menu item under `Devices` that says `Set XY Origin Here` and that could just be a standard part of startup when using a non-homing stage. That way the HCS plugin can be self contained without affecting system-wide settings.

**Comment by nicost** [comment]
Whether this makes sense from a design point of view is above my pay grade.  It has worked well for a decade or so!  Nevertheless, I think that you are completely right that instead of changing the stage's origin, the plugin could simply remember the offset and add that to every stage position it generates.  

I don't see any problems with that change (and you are also right that will give the possibility to remember the offset), other than that it needs very thorough debugging and testing because people will be financially harmed with bugs in this code.

**Comment by nanthony21** [comment]
That sounds good. 

I've got a branch set up now with an option to use the new method or the original method. If the new method is used then the offset is saved and reloaded at startup. If using the original method it will maintain the original behavior of  requiring calibration before enabling movement.

I'll do some testing next week on my setup and then open a pull request for further testing.

**Comment by nicost** [comment]
Pull Request was merged.
