### ISSUE TITLE
Live mode & Stuttering

### ISSUE THREAD

**Issue by Goldensteev** [nicost/micro-manager#40]
I have 3 main light sources : Brightfield, coolLED-direct & coolLED-DMD and for some reason whenever I switch to a channel using the DMD LED my camera window will start turning on and off continuously as shown in attached gif. This error seems to be linked to the autoshutter somehow as disabling it will stop the 'stuttering'.
I have attached 2 Corelogs.  

using version from yesterday although i did notice it happening with previous versions (week or 2 old versions)

using windows 10

can give more anecdotal details if needed. 
[CoreLog20190419T105715_pid14920.txt](https://github.com/nicost/micro-manager/files/3097668/CoreLog20190419T105715_pid14920.txt)
[CoreLog20190419T110834_pid8504.txt](https://github.com/nicost/micro-manager/files/3097669/CoreLog20190419T110834_pid8504.txt)
![stuttering](https://user-images.githubusercontent.com/14848329/56418703-07632580-6298-11e9-9977-b7778ec105c0.gif)

**Comment by nicost** [comment]
It will be much more useful to discuss this on the mailing list.  I am pretty sure this is a configuration issue.  Keep your channel definitions to a bare minimum.  Especially, never add shutter state to a channel definition (otherwise, once the auto shutter functionality changes the state of the shutter, MM will detect that the channel changed and display the image in a new window).
