### ISSUE TITLE
Micromanager freezes on device error during hardware manager initialization.

### ISSUE THREAD

**Issue by nanthony21** [nicost/micro-manager#44]
I'm certain that this used to work properly but lately I have been getting an issue.

If you try to open a configuration in the hardware configuration manager  and a device error occurs then a dialog will appear saying "Error in device {x}. Remove device {x} from the list?"

However this dialog and all other micromanager windows cannot be interacted with since the splash screen reading `Loading devices, please wait...' is still visible.
![Capture](https://user-images.githubusercontent.com/8433487/58285045-9bca1780-7d71-11e9-904c-18d7f4ae7b90.PNG)

This means that the only way to exit micromanager is to kill the process. And the only way to fix a faulty configuration is to remove problematic devices using a text editor.

**Comment by nicost** [comment]
I am not completely sure what is going.  I can reproduce a similat situation, but then can drag the dialog to an area where it can be clicked on.  I now made some changes so that the "Loading devices" message disappears when there is an error while loading the configuration.  However, the behavior is still bad, since the Error dialog appears below the HCW, and I can  not figure out how to move that one to the foreground (without re-writing how that dialog is generated).  

The HCW needs some real work, so I am not sure how much work patching this thing is warranted...
