### ISSUE TITLE
Can no longer run image sequences in runnables

### ISSUE THREAD

**Issue by ctr26** [nicost/micro-manager#72]
Hi again,

After trying my code to take multiple images per each MDA frame it throws an error saying "This operation can not be executed while sequence acquisition is running." The issue is the code does work on the test camera and did indeed work on an old micromanager install.

Here is an example beanshell script. The camera that this script fails on is a Hamamatsu. 

```
acq = mm.getAcquisitionManager();
acq.clearRunnables();


acq.attachRunnable(-1,-1,-1,-1,runnable);
```

Best

Craig

**Comment by nicost** [comment]
What acquisition protocol are you running (please specify as precisely as possible, i.e. nr time points, interval, etc...)?

**Comment by ctr26** [comment]
I've tried with a straight forward multi-d acquisition of 5 frames. A 1 second and 0 second interval produces the same error. Unfortunately I don't have another camera to test this on.

**Comment by nicost** [comment]
I am unsure how this is supposed to work.  The runnable will be executed before each frame is taken.  The runnable starts the sequence, then exits (without waiting for the sequence to finish).  Then, while the sequence is running, the acquisition engine tries to snap an image, which fails with the error message "This operation can not be executed while sequence acquisition is running." That all seems perfectly logical to me, and if something like this worked in the past, it surely was by chance.  

What exactly do you try to accomplish?  B.t.w., this thread belongs on the mailing (micro-manager-general@listssourceforge.net) list rather than here on github, as it is not really code related.

**Comment by ctr26** [comment]
Apologies, the issue was that I'd hard coded the width and height of my image stack causing an error. The above code was my attempt to cut down my code to demonstrate the problem, creating a different one.

Sorry

Craig
