### ISSUE TITLE
[Feature] Live-view FFT Plugin

### ISSUE THREAD

**Issue by ctr26** [nicost/micro-manager#81]
Moving this into it's own thread as per nicost#62 (comment)_

I've written a rough and ready plugin for doing Live FFTs of the live image.

_" just had a look at your MMLiveFFT plugin, but was confused about getting it to work. It only seems to work when Live mode is running when you start the plugin, otherwise no image ever shows up in it."_

This is a bug that I've been meaning to fix and will over xmas.

_"Also, it makes more sense to me to insert this in the plugin menu rather then under the Gearbutton, since it only works on live display, and not on every viewer. "_

Agree, will implement

_"Maybe this makes more sense as an On-The-Fly-Processor (although it would likely not really process the real image, but calculate an FFT and show in a separate window more or less as a side effect."_

I was going to to do the plugin as an on-the-fly processor, originally but I wasn't entirely sure on the behaviour of processors. Particularly on how they respond to per frame processing that takes longer than a frame, does the next frame just skip?

Best

Craig

**Comment by nicost** [comment]
That behavior is up to you. I probably would looks at the "Image Save" plugin ("PipelineSave" in the source code), and use only the RAM saving parts of it.  I would also put the FFT calculating parts on its own thread, and only feed it a new image when that thread is not busy, so that you do not get stuck doing FFTs on old images.  This also would pass the original image through to the Live display without delay. Happy to have a look or help more.
